### ISSUE TITLE
Return object from dart function

### ISSUE THREAD

**Issue by winterdl** [hythl0day/hetu_script#1]
How can we return object from dart functions to hetu script and then use it's returned value from hetu, something like LuaValue of Luaj lib.

**Comment by hythl0day** [comment]
Just return the value from Dart within the external functions.

I modified the example to show you how to get a value/object from dart:

```
import 'package:hetu_script/hetu_script.dart';

void main() async {
  var hetu = await Hetu.init(externalFunctions: {
    'dartHello': (HT_Instance instance, List<dynamic> args) {
      return {'dartValue': 'hello'};
    },
  });
  hetu.eval(
      'external fun dartHello\n'
      'proc main {\n'
      '  var dartValue = dartHello()\n'
      '  print(typeof(dartValue))'
      '  print(dartValue)'
      '\n}',
      invokeFunc: 'main');
}
```

**Comment by winterdl** [comment]
Thank you for reply, it's all my need now.

In the second snippet, could you explain more how to pass pointer a instance of class to Hetu.

With Luaj, I could use something like this to coerce a Java type to LuaValue, and could use public members of that object.

`Globals globals = JsePlatform.standardGlobals();   
globals.set("image", CoerceJavaToLua.coerce(
        new BufferedImage(30,40,BufferedImage.TYPE_INT_RGB)));
LuaValue chunk = globals.load(
        "print(image:getWidth(), image:getHeight());");`

With Hetu script, if I want to expose some method of a userapi, I could use externalFunctions, ex:

`var hetu = await Hetu.init(externalFunctions: {
    'userapi_method1': (HT_Instance instance, List<dynamic> args) {
      ...
    },
 'userapi_method2': (HT_Instance instance, List<dynamic> args) {
      ...
    },
  });`

It's very helpful if we could expose object with externalFunctions, I could return object from the code like this and call public members of returned object.

`var hetu = await Hetu.init(externalFunctions: {
    'get_user': (HT_Instance instance, List<dynamic> args) {
      ...
    }
  });`

**Comment by hythl0day** [comment]
If you omit the type annotation in Hetu, you get an object of dynamic type, which can be assigned with any value (even an unknown object from Dart).
And you can declare external functions globally or within a class.

In fact, Hetu's core right now is just a wrapper above Dart, for example, the List in Hetu is a List Object of Dart.

```
class List extends Value {
	
	external get length: num
	
	get isEmpty: bool {
		return length == 0
	}
	
	get isNotEmpty: bool {
		return length != 0
	}
	
	get first: any {
    if (length > 0){
      return elementAt(0)
    }
	}
	
	get last: any {
    if (length > 0){
      return elementAt(length - 1)
    }
  }
	
	fun contains(value): bool {
		return indexOf(value) != -1
	}
	
	external fun add(... args)
	
	external fun clear()
	
	external fun removeAt(index: num)
	
	external fun indexOf(value): num
	
	external fun elementAt(index: num): any
}
```

You can check Hetu's library in the 'hetu_lib' folder, which is basically how to wrap Dart object and use them in Hetu.

As you can see, Hetu is very simple, It's just for learning purpose, It's not an efficient language VM like lua right now. It is usable only if you don't have any heavy tasks with performance requirements.

**Comment by winterdl** [comment]
Thank you for your code, I think now I could try to porting my simple android crawler app currenly used Lua to define rules when parsing html.

**Comment by hythl0day** [comment]
> Thank you for your code, I think now I could try to porting my simple android crawler app currenly used Lua to define rules when parsing html.

There are some bugs in the current source, I have fixed them, but you might need git pull.

**Comment by winterdl** [comment]
Hello,

How to register custom class like List or Map, I've read and follow the code from repo, but I didn't understand much.

Could you please review my code, I could not instance HTVal_User class, so when I run the code, I get: 

`null, null`

```
import 'package:hetu_script/hetu_script.dart';
import 'package:hetu_script/src/lexicon.dart';

void main() async {
  var hetu = await Hetu.init(externalFunctions: {
    'dartHello': (HT_Instance instance, List<dynamic> args) {
      return {'dartValue': 'hello'};
    },
    ...MyBaseBinding.dartFunctions
  });

  for (final file in myCoreLibs.keys) {
    hetu.eval(myCoreLibs[file], fileName: file);
  }

  hetu.evalf("./test/user.ht", invokeFunc: 'main');
}

// dart class wanted to expose to hetu script
class User {
  String _time;

  User() {
    _time = DateTime.now().toIso8601String();
  }

  String getTime() {
    return _time;
  }
}

// binding
class MyBaseBinding {
  static Map<String, HT_External> dartFunctions = {
    'User.getTime': HTVal_User._getTime
  };
}

final Map<String, String> myCoreLibs = const {
  'user.ht': r'''class User extends Value {
    external fun getTime(): any
  }'''
};

class HTVal_User extends HTVal_Value {
  String valueType;

  HTVal_User(User value, int line, int column, Interpreter interpreter,
      {this.valueType})
      : super(value, HT_Lexicon.CLASS, line, column, interpreter) {
    valueType ??= HT_Lexicon.ANY;
  }

  static dynamic _getTime(HT_Instance instance, List<dynamic> args) {
    var userObj = (instance as HTVal_User);
    User user = userObj?.value;

    return user?.getTime();
  }
}
```

hetu script file user.ht

```
proc main {
  var user = User()
  print(user.getTime())

  var user2 = User()
  print(user2.getTime())
}
```
