### ISSUE TITLE
toString() on num not working

### ISSUE THREAD

**Issue by fpv999** [hythl0day/hetu_script#4]
```
fun main() {  
    var hello: num  
    hello = 3
    print( hello.toString() )
}
```

results in:

```
flutter: hetu error: [line: 4, column: 12]
Could not acess private member "__method__toString"

```

**Comment by fpv999** [comment]
so does it mean, that methods in parent class (Value is a parent to Num) are private by default?

**Comment by hythl0day** [comment]
> so does it mean, that methods in parent class (Value is a parent to Num) are private by default?

I think it's a bug, I'll look into it today.

**Comment by fpv999** [comment]
so far, it's not fixed
