### ISSUE TITLE
Support operator for common class like String

### ISSUE THREAD

**Issue by winterdl** [hythl0day/hetu_script#6]
I could not using "+" operator to append string, it's good if the lib support it, by now I have to using externalFunctions to append two string.

Thank you.

**Comment by fpv999** [comment]
try .toStringAsFixed() for a num.
That's because https://github.com/hythl0day/hetu_script/issues/4 is still not fixed :/

**Comment by winterdl** [comment]
Sorry because I've tested with case append string and num toString, it's run ok with toStringAsFixed.

**Comment by fpv999** [comment]
I've tested again, and it looks like that .toString() works in 0.0.2+4

**Comment by hythl0day** [comment]
I tested in 0.0.2+4, it's okay.

```typescript
proc main() {
  var first = 'first';
  var last = 'last';

  print(first + last);

  print(3.toString() + first);

  print(233.toString() + true.toString());

  print(['hello, world'].toString() + 42.toString());
}
```
